# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.5
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [manual]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: cargo fmt
        description: Format Rust code with rustfmt
        args: ['--manifest-path', 'src-tauri/Cargo.toml']
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        description: Check Rust code compiles
        args: ['--manifest-path', 'src-tauri/Cargo.toml']
      - id: clippy
        name: cargo clippy
        description: Lint Rust code with clippy
        args: ['--manifest-path', 'src-tauri/Cargo.toml', '--all-targets', '--all-features', '--', '-D', 'warnings']
